name: CI con AutoCommit

on:
  push:
    branches: ["Parte-2"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  python_tests_actualizar_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install pytest

      - name: Ejecutar script de tests y actualizar README
        run: python update_readme.py

      - name: Commit automático del README actualizado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README with test results"
          file_pattern: README.md
