name: Generar y publicar documentaci칩n Doxygen

on:
  workflow_run:
    workflows: ["CI con AutoCommit"]
    types:
      - success

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar Doxygen y Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generar documentaci칩n Doxygen
        run: doxygen docs/Doxyfile

      - name: Commit autom치tico de la documentaci칩n Doxygen
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Doxygen documentation"
          file_pattern: docs/**
