name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - Parte-2
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: Parte-2
          folder: docs/html
          config_file: docs/Doxyfile
          doxygen_version: 1.9.8