name: Doxygen GitHub Pages

on:
  push:
    branches: [Parte-2] # O añade más ramas si lo necesitas

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Doxygen documentation
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: "."
          doxyfile-path: "docs/Doxyfile"
