name: CI + Doxygen

on:
  push:
    branches: ["Parte-2"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  actualizar-tests-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install pytest

      - name: Ejecutar script de tests y actualizar README
        run: python update_readme.py

      - name: Commit automático del README actualizado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualización README con resultados de tests"
          file_pattern: "README.md"


  actualizar-documentacion:
    runs-on: ubuntu-latest
    needs: actualizar-tests-readme
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar Doxygen y Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generar documentación Doxygen
        run: doxygen docs/Doxyfile

      - name: Pull ultimos cambios
        run: git pull

      - name: Commit automático de documentación
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualización documentación Doxygen"
          file_pattern: "docs/**"
