name: CI + Doxygen + MkDocs

on:
  push:
    branches: ["Parte-2"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # Job para ejecutar tests y actualizar README
  actualizar-tests-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install pytest

      - name: Ejecutar script de tests y actualizar README
        run: python update_readme.py

      - name: Commit automático del README actualizado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualización README con resultados de tests"
          file_pattern: "README.md"

  # Job para generar y actualizar documentación Doxygen
  actualizar-docs-doxygen:
    runs-on: ubuntu-latest
    needs: actualizar-tests-readme
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Instalar Doxygen y Graphviz y TeX Live(para PDF)
        run: |
          sudo apt update
          sudo apt install -y doxygen graphviz

      - name: Generar documentación Doxygen
        run: doxygen docs/Doxyfile
                  
      - name: Pull ultimos cambios
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull

      - name: Commit automático de documentación de Doxygen
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualización documentación Doxygen"
          file_pattern: "docs/**"
  
  # Job para generar y actualizar documentación MkDocs
  actualizar-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install pdoc
          
      - name: Generar documentación Markdown con pdoc
        run: |
          pdoc --output-dir docs --format markdown markdown_modulo
